### ISSUE TITLE
Ideia de recebimento de notificação

### ISSUE THREAD

**Issue by HugoOliveiraSoares** [Grupo-Flare/Sistemadenotificacao#12]
Conversando com o @N0T-NULL  pensamos na ideia de disponibilizar ao aluno diversas formas de recebimento de notificação, como por exemplo por whatsapp, email, notification Push (que pode ser a forma padrão) ou ate o Teams. Também poderíamos pergunta-lo qual é o meio que ele prefere.

Nessa ultima ideia podemos criar um bot com o *Power Virtual Agents* para enviar as notificações no chat do aluno.
A mensagem do tipo urgente ela notifica de **2 em 2 minutos por 20 minutos** ou ate a pessoa visualizar.

![image](https://user-images.githubusercontent.com/33163249/158373538-4cf1d24c-e22a-4534-907d-aac4e3df9457.png)

![image](https://user-images.githubusercontent.com/33163249/158373650-e3c1a99e-57e0-4162-b297-7e35a67154a1.png)

![image](https://user-images.githubusercontent.com/33163249/158373670-59756a37-5832-4f35-8bcf-59c53d05edb1.png)

**Comment by diego282** [comment]
Gostei bastante desse bot, e como vocês trouxeram a ideia visualmente achei muito legal, levem a ideia ao grupo para avaliarmos
