### ISSUE TITLE
Prototipação

### ISSUE THREAD

**Issue by HugoOliveiraSoares** [Grupo-Flare/Sistemadenotificacao#2]
Iniciar o protótipo com as telas do projeto.

- [x] Tela de login
- [x] Home
- [x] Canal
- [x] Admin - Home
- [x] Admin - Cadastro
- [x] Admin - Publicação

**Comment by caiohferreiradev** [comment]
**Atualização em 11/03**: enviamos um e-mail para o cliente para conseguir o guia de branding (marca) da faculdade. Além disso, ficou alinhado que o Giovanni Évora irá construir o protótipo utilizando o Adobe Illustrator, que será posteriormente projetado no Figma por todos os participantes do projeto que indicaram afinidade na etapa de prototipação.

**Comment by diego282** [comment]
Em e-mail encaminhado a secretaria sobre o guia de branding fui informado que já foi solicitado e que o mesmo deve ser repassado em breve para o grupo.

**Comment by HugoOliveiraSoares** [comment]
**Atualização em 15/03**: Recebemos o guia de branding da instituição, apesar da futura mudança da marca iremos permanecer com a atual. Apesar do manual ser da Dom Helder, as instruções são as mesmas para a EMGE.
Segue abaixo o material:

[ManualDeBranding.pdf](https://github.com/HugoOliveiraSoares/Sistemadenotificacao/files/8255552/Manual.Dom.Helder.pdf)
 
![EMGE_PNG_ALTA](https://user-images.githubusercontent.com/33163249/158430690-e76e91f5-ab9f-40e8-9f77-bb0a1d44e463.png)

**Comment by diego282** [comment]
E-mail solicitando guia de marca respondido com permissão e as guias anexas, abaixo segue o escopo do e-mail


</div><div id=":1aq"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class=""><div class="aHl" style="margin-left: -38px;"></div><div id=":1bs" tabindex="-1"></div><div id=":1ao" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":1ap" class="a3s aiL msg-2513318896724374640" style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div class="adM"></div><div dir="ltr"><div class="adM"></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Olá Diego, boa tarde!</div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">A definição sobre a nova marca deverá ocorrer no segundo semestre deste ano. </div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">No momento, continuamos com a logo da EMGE, que segue em anexo. </div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Sobre o guia para uso, encaminho o material da Dom Helder. As mesmas orientações se aplicam para a marca da EMGE.</div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Qualquer dúvida, estamos à disposição.</div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Att.</div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div><div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Patrícia </div></div></div></div></div></div>
</body>
</html>

**Comment by diego282** [comment]
Prototipação concluída no dia 29/03/2022 , feito no figma.

Além da tela de login e cadastro, o mesmo foi dividido em três grupos ou Hieraquias sendo eles:

Alunos : Histórico de notificação, notas, ativar notificação, cancelar ou atualizar as mesmas
Professores: Lancamentos e notas e mensagens
Reitoria/coordenador:  Criação,update e delete de canais e usuários permitidos, liberação de envio para terceiros, envio de mensagens e muito mais.
