### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by HugoOliveiraSoares** [Grupo-Flare/Sistemadenotificacao#3]
Iniciar a documentação demonstrando as tarefas já realizadas e o que o projeto ira fazer e como tudo funciona

**Comment by diego282** [comment]
Atualização 15/03: Reunião marcada para 15/03/2022 de 17:30 ás 18h, abaixo o escopo e-mail
Conversar será online:   https://teams.live.com/meet/9353201664480

Sobre o designer ser tem alguma cor, layout a ser usado, ou o grupo pode definir!?

Isso é parte do trabalho....

 
Hoje de 17:30 às 18:00??


Todos podem participar sim.
