### ISSUE TITLE
Definir tecnologias a serem utilizadas

### ISSUE THREAD

**Issue by HugoOliveiraSoares** [Grupo-Flare/Sistemadenotificacao#4]

**Comment by caiohferreiradev** [comment]
**Atualização em 11/03**: no primeiro momento a equipe levantou que as tecnologias a serem utilizadas serão HTML, CSS, PHP, JavaScript, Heroku (hospedagem) e MySQL (banco de dados). As afinidades de cada um estão descritas abaixo.

- Caio : HTML, CSS e JS, Prototipação;
- Diego: HTML, JS, PHP, MySQL, Prototipação;
- Matheus: HTML, CSS, Prototipação, pouco JS
- Marco Aurélio: HTML, CSS, Prototipação
- Kamilah: HTML, CSS, Prototipação, pouco JS
- Hugo: PHP, JS, Heroku, MySQL, Postgresql, Java(SpringBoot)
- Giovanni: Design e UX,Prototipação, HTML e CSS.
