### ISSUE TITLE
Conversar com o cliente

### ISSUE THREAD

**Issue by HugoOliveiraSoares** [Grupo-Flare/Sistemadenotificacao#5]
Discutir com o cliente qual a sua necessidade e as possíveis soluções

**Comment by caiohferreiradev** [comment]
@HugoOliveiraSoares, pode adicionar todo mundo por aqui? Acredito que não temos permissão para nos atribuir a esse issue.

**Comment by caiohferreiradev** [comment]
**Atualização**: enviamos um e-mail para o cliente (Cristiano Lacerda) no dia 11/03, aguardamos as considerações do mesmo.

**Comment by HugoOliveiraSoares** [comment]
> @HugoOliveiraSoares, pode adicionar todo mundo por aqui? Acredito que não temos permissão para nos atribuir a esse issue.

@caioh-ferreira vou dar uma olhada nas configurações dos colaboradores, se não encontrar nada eu vou atribuindo as issues para cada um

**Comment by caiohferreiradev** [comment]
Deu certo, @HugoOliveiraSoares, muito obrigado. Logo que adicionei as anotações, fui atribuído automaticamente como contribuidor na issue.

**Comment by HugoOliveiraSoares** [comment]
> Deu certo, @HugoOliveiraSoares, muito obrigado. Logo que adicionei as anotações, fui atribuído automaticamente como contribuidor na issue.

@caioh-ferreira  Ótimo! :sunglasses:

**Comment by diego282** [comment]
**Atualização**: 

**O que você espera do projeto?**
Sistema web de gerenciamento de notificações (categoria de alertas, alertas, usuários)
Sistema mobile  para notificação da instituição (cadastro contendo RA, configuração das categorias que deseja ser notificado, notificações)

**Qual o design espera da aplicação?**

Não entendi a pergunta? Acredito que esse deve ser uma proposta do grupo

**Alguma tecnologia específica a ser usada?**

O sistema deve funcionar de forma independente de qualquer outro sistema legado da instituição, então pode ser desenvolvido em qualquer tecnologia a ser definida e justificada pelo grupo

**Especificações esperadas, entre outras perguntas.**

Podemos marcar uma agenda de 30 minuto para este levantamento.

Aguardando resposta para marcação de reunião.

**Comment by HugoOliveiraSoares** [comment]
### Perguntas para a reunião

- Como podemos saber em qual curso, disciplinas, período e turma o aluno pertence. Existe alguma API, seja ela da instituição ou do teams?

- Quando um professor necessita passar uma informação para a instituição, como é feita essa comunicação?
